stages:
  - build
  - package
  - code_quality

build:ubuntu:
  image: gcc:latest
  allow_failure: false
  before_script:
    - apt-get update -y
    - apt-get install cmake libncurses5-dev libncursesw5-dev -y
  scriptï¼š
    - cmake.
    - make

package:source:
  image: ubuntu:bionic
  dependencies:
    - build:ubuntu
